### ISSUE TITLE
Dependency Injection stops working with this NuGet in project

### ISSUE THREAD

**Issue by Moerup** [vitalybibikov/AzureExtensions.Swashbuckle#34] opened 2020-08-13 09:48 UTC
I've been battling with an issue for a long time in my V3 function and I've finally found the reason

When I include this NuGet in my project, Startup.cs is never called. It's not exporting the extensions correctly to extensions.json on build where all the services are registered. The file is simply empty.

I've think I have tried every single thing on google to get this to work, but nothing helps.
Would love to have Swagger in my solution, hope you can help figure out what's wrong!

**.csproj**
```<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>TestFunction.xml</DocumentationFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AzureExtensions.Swashbuckle" Version="3.2.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="MongoDB.Bson" Version="2.11.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.11.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.7.1" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  
</Project>
```

**SwashBuckleStartup**
```
[assembly: WebJobsStartup(typeof(SwashBuckleStartup))]

namespace TicketMaster
{
    internal class SwashBuckleStartup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            //Register the extension
            builder.AddSwashBuckle(Assembly.GetExecutingAssembly(), opts =>
            {
                opts.SpecVersion = OpenApiSpecVersion.OpenApi3_0;
                opts.AddCodeParameter = true;
                opts.PrependOperationWithRoutePrefix = true;
                opts.XmlPath = "TestFunction.xml";
                opts.Documents = new[]
                {
                    new SwaggerDocument
                    {
                        Name = "v1",
                        Title = "Swagger document",
                        Description = "Swagger test document",
                        Version = "v2"
                    }
                };
                opts.Title = "Swagger Test";
                //opts.OverridenPathToSwaggerJson = new Uri("http://localhost:7071/api/Swagger/json");
                opts.ConfigureSwaggerGen = (x =>
                {
                    x.CustomOperationIds(apiDesc =>
                    {
                        return apiDesc.TryGetMethodInfo(out MethodInfo methodInfo)
                            ? methodInfo.Name
                            : new Guid().ToString();
                    });
                });
            });
        }
    }
}
```

If I remove the NuGet and create a Startup.cs like this:

```
using System;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using TicketMaster.API.Interfaces;
using TicketMaster.API.Services;

[assembly: FunctionsStartup(typeof(TicketMaster.API.Startup))]
namespace TicketMaster.API
{
    public class Startup : FunctionsStartup
    {
        public Startup() { }

        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IAuthenticationService, AuthenticationService>();
        }
    }
}
```

The extensions.json gets generated correctly and the Startup.cs is correctly called

Let me know if you need more info

**Comment by vitalybibikov** [comment] 2020-08-14 11:15
Please, provide a repro, it works at the moment in 3 of my projects. 
I've tried to create an empty project with your startup - everything is OK in my case.

**Comment by Ma3yTa** [comment] 2020-08-26 06:57
I have the same problem with a combination of packages:

```
<PackageReference Include="AzureExtensions.Swashbuckle" Version="3.2.2" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
```

```csharp
using AzureFunctions.Extensions.Swashbuckle;
using FunctionApp;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using System.Reflection;

[assembly: FunctionsStartup(typeof(Startup))]
namespace FunctionApp
{
    internal class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.AddSwashBuckle(Assembly.GetExecutingAssembly());
        }
    }
}

```

**Comment by rari2012** [comment] 2020-08-27 10:19
Hey There,
caught the same issue.
My Startup is called corrctly, but the aditional Swagger Startup is never called. Can't figure out why.

**Comment by rari2012** [comment] 2020-08-27 11:33
By the way - i originally downloaded your Repo from here and Build it - it failed with the same message like the others here.
Will debug and try to fix it.

**Comment by rari2012** [comment] 2020-08-27 13:33
Okay- 
My findings:
System.Text.Json must stay at 4.7.0 
In case of your Startup is not loading check for <UserSecretsId></UserSecretsId> in your csprof and if found - remove it.
(https://github.com/Azure/azure-functions-vs-build-sdk/issues/389)
If you plan on keep using it - i found this article: https://damienbod.com/2020/07/12/azure-functions-configuration-and-secrets-management/

In case it still doesn't load you also may add there <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
This will ensure packages are nor cleanded out if doublicates are found.
Hope this is helpful to you as well.

**Comment by vitalybibikov** [comment] 2020-08-31 09:20
<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> is an external issue of the functions itself.

As well as inability to update to System.Text.Json higher than 4.7.0 due to some project refs.

But they simply cause build issues. 

Still can not reproduce, please provide a repro.

**Comment by dandzina** [comment] 2020-09-02 16:55
I had a issue with any project that depended on AspNetCore.App framework reference in functions v3 where DI would break (or more specifically, Microsoft.Azure.Functions.Extensions 's FunctionsStartup just never gets called).
It boiled down to having to explicitly add package references to my functions project for:

    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.18" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.6" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.7" />

Which were otherwise included as dependent packages anyway by Microsoft.NET.Sdk.Functions v3.x, but the dependencies are loaded by nuget only at minimum 2.x version levels that arenot compatible with aspnetcore 3.   

Without any use of a package that requires FrameworkRefrerence to Microsoft.AspNetCore.App , everything is fine -- but as soon as some package (lke this swagger package) inclues it, FunctionsStartup breaks and so goes DI.

**Comment by vitalybibikov** [comment] 2020-09-02 19:01
All looks like it is a problem with functions itself.

I can see similar issues in there.
e.g. https://github.com/Azure/azure-functions-host/issues/6587

**Comment by vitalybibikov** [comment] 2020-09-03 14:05
Closed as it looks like a global issue, not related to this Nuget in particular.

**Closed by vitalybibikov** 2020-09-03 14:05 UTC
